"""foreign db

Revision ID: 6eb3f620bf16
Revises: 80ba1b33450b
Create Date: 2023-05-14 21:13:57.539538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb3f620bf16'
down_revision = '80ba1b33450b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
